#!/usr/bin/env bash

dir="$(dirname "$(realpath "$0")")"

DEBUG=0

if [ ! -f wofi-dracula/style.css ]; then
  git submodule update --init
fi

prompt() {
  read -p "$1 "
  echo    # (optional) move to a new line
  [[ "$REPLY" =~ ^[Yy]$ ]]
}

link() {
  source="$1"
  abssource="${dir}/${source}"
  target="$2"
  if [ "$DEBUG" = "1" ]; then
    echo "Source ${source}"
    echo "Target ${target}"
  fi
  mkdir -p "$(dirname "${target}")"
  if [ -L "${target}" ]; then
    olddest="$(readlink "${target}")"
    if [ "${olddest}" == "${abssource}" ]; then
      echo "✅ '${source}' already linked"
      return
    else
      if prompt "Link for '$1' currently points to '${olddest}'. Overwrite? "; then
        rm "${target}"
      else
        echo "⚠️ Skipped ${source}"
        return
      fi
    fi
  elif [ -f "${target}" ]; then
    if prompt "Overwrite '${target}' with link to '${source}'? "; then
      rm "${target}"
    else
      echo "⚠️ Skipped ${source}"
      return
    fi
  fi
  ln -sf "${abssource}" "${target}"
  echo "✅ Linked '${source}'"
}

mkdir -p ~/.local/bin

for i in scripts/*; do
  chmod +x $i
done

link git ~/.config/git/config
link zshrc ~/.zshrc
link readline ~/.inputrc
link sway ~/.config/sway/config
link tmux ~/.tmux.conf
link wofi-dracula/style.css ~/.config/wofi/style.css
link starship.toml ~/.config/starship.toml
link helix/helix.toml ~/.config/helix/config.toml
link helix/languages.toml ~/.config/helix/languages.toml
link waybar/config.jsonc ~/.config/waybar/config.jsonc
link waybar/style.css ~/.config/waybar/style.css
link alacritty.toml ~/.config/alacritty/alacritty.toml
link gdb ~/.config/gdb/gdbinit
link gitignore ~/.config/git/ignore
link cargo.toml ~/.cargo/config.toml
link tmate.conf ~/.tmate.conf
link foot.ini ~/.config/foot/foot.ini
link scripts/wait-and-start-waybar.sh ~/.local/bin/wait-and-start-waybar.sh
link scripts/change-brightness.pl ~/.local/bin/change-brightness.pl
link ironbar/config.toml ~/.config/ironbar/config.toml
link mako ~/.config/mako/config

if [ -d /usr/share/themes ]; then
  if [ ! -d /usr/share/themes/Dracula ]; then
    echo "Downloading Dracula gtk theme"
    wget https://github.com/dracula/gtk/archive/master.zip
    echo "Unzipping..."
    unzip master.zip &> /dev/null
    rm master.zip
    echo "Moving to /usr/share/themes"
    sudo mv gtk-master /usr/share/themes/Dracula
  fi

  if [ ! -d /usr/share/icons/Dracula ]; then
    echo "Downloading Dracula icon theme"
    wget https://github.com/dracula/gtk/files/5214870/Dracula.zip
    echo "Unzipping..."
    unzip Dracula.zip &> /dev/null
    rm Dracula.zip
    echo "Moving to /usr/share/icons"
    sudo mv Dracula /usr/share/icons
  fi
fi

if ! grep $USER /etc/passwd | grep zsh > /dev/null; then
  echo "Making ZSH the default shell"
  chsh -s "$(which zsh)"
fi
