#!/usr/bin/env sh

dir="$(dirname "$(realpath "$0")")"

DEBUG=0

if [ ! -f wofi-dracula/style.css ]; then
  git submodule update --init
fi

function prompt() {
  read -p "$1 " -n 1 -r
  echo    # (optional) move to a new line
  [[ "$REPLY" =~ ^[Yy]$ ]]
}

function link() {
  source="$1"
  abssource="${dir}/${source}"
  target="$2"
  if [ "$DEBUG" = "1" ]; then
    echo "Source ${source}"
    echo "Target ${target}"
  fi
  mkdir -p "$(dirname "${target}")"
  if [ -L "${target}" ]; then
    olddest="$(readlink "${target}")"
    if [ "${olddest}" == "${abssource}" ]; then
      echo "✅ '${source}' already linked"
      return
    else
      if prompt "Link for '$1' currently points to '${olddest}'. Overwrite? "; then
        rm "${target}"
      else
        echo "⚠️ Skipped ${source}"
        return
      fi
    fi
  elif [ -f "${target}" ]; then
    if prompt "Overwrite '${target}' with link to '${source}'? "; then
      rm "${target}"
    else
      echo "⚠️ Skipped ${source}"
      return
    fi
  fi
  ln -sf "${abssource}" "${target}"
  echo "✅ Linked '${source}'"
}

link git ~/.config/git/config
link zshrc ~/.zshrc
link readline ~/.inputrc
link sway ~/.config/sway/config
link tmux ~/.tmux.conf
link wofi-dracula/style.css ~/.config/wofi/style.css
link starship.toml ~/.config/starship.toml
link helix/helix.toml ~/.config/helix/config.toml
link helix/languages.toml ~/.config/helix/languages.toml
link waybar/config.jsonc ~/.config/waybar/config.jsonc
link waybar/style.css ~/.config/waybar/style.css
link alacritty.toml ~/.config/alacritty/alacritty.toml
link gdb ~/.config/gdb/gdbinit
link gitignore ~/.config/git/ignore

if [ ! -d ~/.themes/dracula ]; then
  mkdir -p ~/.themes
  pushd ~/.themes
  git clone https://github.com/dracula/gtk dracula --depth=1
  popd
fi

if ! grep $USER /etc/passwd | grep zsh > /dev/null; then
  echo "Making ZSH the default shell"
  chsh -s "$(which zsh)"
fi

