[[language]]
name = "gas"
indent = { tab-width = 8, unit = "\t" }

[[language]]
name = "haskell"
scope = "source.haskell"
auto-format = true
injection-regex = "hs|haskell"
file-types = ["hs", "hs-boot", "hsc"]
roots = ["Setup.hs", "stack.yaml", "cabal.project", "hie.yaml"]
shebangs = ["runhaskell", "stack"]
comment-token = "--"
block-comment-tokens = { start = "{-", end = "-}" }
language-servers = [ "haskell-language-server" ]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "lean"
scope = "source.lean"
roots = ["lakefile.toml", "lakefile.lean", "lean-toolchain"]
auto-format = true

[language-server.lean]
args = ["--server"]

[language-server.haskell-language-server]
args = ["--lsp"]
command = "haskell-language-server-wrapper"
config = { haskell.formattingProvider = "fourmolu" }

[[language]]
name = "lean"
scope = "source.lean"
file-types = ["lean"]
roots = ["lakefile.lean", "lakefile.toml", "lean-toolchain"]
language-servers = ["lean-lake"]

[language-server.lean-lake]
command = "lake"
args = ["env", "lean", "--server"]
